from __future__ import annotations

LANG_KEYS = ("en", "hi", "sa")

TITHI_NAMES = {
    "en": [
        "Pratipada",
        "Dvitiya",
        "Tritiya",
        "Chaturthi",
        "Panchami",
        "Shashthi",
        "Saptami",
        "Ashtami",
        "Navami",
        "Dashami",
        "Ekadashi",
        "Dvadashi",
        "Trayodashi",
        "Chaturdashi",
        "Purnima",
        "Pratipada (Krishna)",
        "Dvitiya (Krishna)",
        "Tritiya (Krishna)",
        "Chaturthi (Krishna)",
        "Panchami (Krishna)",
        "Shashthi (Krishna)",
        "Saptami (Krishna)",
        "Ashtami (Krishna)",
        "Navami (Krishna)",
        "Dashami (Krishna)",
        "Ekadashi (Krishna)",
        "Dvadashi (Krishna)",
        "Trayodashi (Krishna)",
        "Chaturdashi (Krishna)",
        "Amavasya",
    ],
    "hi": [
        "प्रतिपदा",
        "द्वितीया",
        "तृतीया",
        "चतुर्थी",
        "पंचमी",
        "षष्ठी",
        "सप्तमी",
        "अष्टमी",
        "नवमी",
        "दशमी",
        "एकादशी",
        "द्वादशी",
        "त्रयोदशी",
        "चतुर्दशी",
        "पूर्णिमा",
        "प्रतिपदा (कृष्ण)",
        "द्वितीया (कृष्ण)",
        "तृतीया (कृष्ण)",
        "चतुर्थी (कृष्ण)",
        "पंचमी (कृष्ण)",
        "षष्ठी (कृष्ण)",
        "सप्तमी (कृष्ण)",
        "अष्टमी (कृष्ण)",
        "नवमी (कृष्ण)",
        "दशमी (कृष्ण)",
        "एकादशी (कृष्ण)",
        "द्वादशी (कृष्ण)",
        "त्रयोदशी (कृष्ण)",
        "चतुर्दशी (कृष्ण)",
        "अमावस्या",
    ],
    "sa": [
        "प्रतिपदा",
        "द्वितीया",
        "तृतीया",
        "चतुर्थी",
        "पञ्चमी",
        "षष्ठी",
        "सप्तमी",
        "अष्टमी",
        "नवमी",
        "दशमी",
        "एकादशी",
        "द्वादशी",
        "त्रयोदशी",
        "चतुर्दशी",
        "पूर्णिमा",
        "प्रतिपदा (कृष्ण)",
        "द्वितीया (कृष्ण)",
        "तृतीया (कृष्ण)",
        "चतुर्थी (कृष्ण)",
        "पञ्चमी (कृष्ण)",
        "षष्ठी (कृष्ण)",
        "सप्तमी (कृष्ण)",
        "अष्टमी (कृष्ण)",
        "नवमी (कृष्ण)",
        "दशमी (कृष्ण)",
        "एकादशी (कृष्ण)",
        "द्वादशी (कृष्ण)",
        "त्रयोदशी (कृष्ण)",
        "चतुर्दशी (कृष्ण)",
        "अमावास्या",
    ],
}

NAKSHATRA_NAMES = {
    "en": [
        "Ashwini",
        "Bharani",
        "Krittika",
        "Rohini",
        "Mrigashira",
        "Ardra",
        "Punarvasu",
        "Pushya",
        "Ashlesha",
        "Magha",
        "Purva Phalguni",
        "Uttara Phalguni",
        "Hasta",
        "Chitra",
        "Swati",
        "Vishakha",
        "Anuradha",
        "Jyeshtha",
        "Mula",
        "Purva Ashadha",
        "Uttara Ashadha",
        "Shravana",
        "Dhanishta",
        "Shatabhisha",
        "Purva Bhadrapada",
        "Uttara Bhadrapada",
        "Revati",
    ],
    "hi": [
        "अश्विनी",
        "भरणी",
        "कृत्तिका",
        "रोहिणी",
        "मृगशीर्ष",
        "आर्द्रा",
        "पुनर्वसु",
        "पुष्य",
        "आश्लेषा",
        "मघा",
        "पूर्वा फाल्गुनी",
        "उत्तरा फाल्गुनी",
        "हस्त",
        "चित्रा",
        "स्वाती",
        "विशाखा",
        "अनुराधा",
        "ज्येष्ठा",
        "मूल",
        "पूर्वाषाढ़ा",
        "उत्तराषाढ़ा",
        "श्रवण",
        "धनिष्ठा",
        "शतभिषा",
        "पूर्व भाद्रपदा",
        "उत्तर भाद्रपदा",
        "रेवती",
    ],
    "sa": [
        "अश्विनी",
        "भरणी",
        "कृत्तिका",
        "रोहिणी",
        "मृगशीर्षा",
        "आर्द्रा",
        "पुनर्वसु",
        "पुष्य",
        "आश्लेषा",
        "मघा",
        "पूर्वफल्गुनी",
        "उत्तरफल्गुनी",
        "हस्ता",
        "चित्रा",
        "स्वाती",
        "विशाखा",
        "अनुराधा",
        "ज्येष्ठा",
        "मूल",
        "पूर्वाषाढा",
        "उत्तराषाढा",
        "श्रवणा",
        "धनिष्ठा",
        "शतभिषक्",
        "पूर्वभाद्रपदा",
        "उत्तरभाद्रपदा",
        "रेवती",
    ],
}

YOGA_NAMES = {
    "en": [
        "Vishkambha",
        "Priti",
        "Ayushman",
        "Saubhagya",
        "Shobhana",
        "Atiganda",
        "Sukarma",
        "Dhriti",
        "Shoola",
        "Ganda",
        "Vriddhi",
        "Dhruva",
        "Vyaghata",
        "Harshana",
        "Vajra",
        "Siddhi",
        "Vyatipata",
        "Variyana",
        "Parigha",
        "Shiva",
        "Siddha",
        "Sadhya",
        "Shubha",
        "Shukla",
        "Brahma",
        "Indra",
        "Vaidhriti",
    ],
    "hi": [
        "विष्कम्भ",
        "प्रीति",
        "आयुष्मान",
        "सौभाग्य",
        "शोभन",
        "अतिगण्ड",
        "सुकर्मा",
        "धृति",
        "शूल",
        "गण्ड",
        "वृद्धि",
        "ध्रुव",
        "व्याघात",
        "हर्षण",
        "वज्र",
        "सिद्धि",
        "व्यतीपात",
        "वरीयान",
        "परिघ",
        "शिव",
        "सिद्ध",
        "साध्य",
        "शुभ",
        "शुक्ल",
        "ब्रह्म",
        "इन्द्र",
        "वैधृति",
    ],
    "sa": [
        "विष्कम्भ",
        "प्रीति",
        "आयुष्मान",
        "सौभाग्य",
        "शोभन",
        "अतिगण्ड",
        "सुकर्मा",
        "धृति",
        "शूल",
        "गण्ड",
        "वृद्धि",
        "ध्रुव",
        "व्याघात",
        "हर्षण",
        "वज्र",
        "सिद्धि",
        "व्यतीपात",
        "वरीयान्",
        "परिघ",
        "शिव",
        "सिद्ध",
        "साध्य",
        "शुभ",
        "शुक्ल",
        "ब्रह्म",
        "इन्द्र",
        "वैधृति",
    ],
}

VAAR_NAMES = {
    "en": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "hi": ["सोमवार", "मंगलवार", "बुधवार", "गुरुवार", "शुक्रवार", "शनिवार", "रविवार"],
    "sa": ["सोमवासर", "मङ्गलवासर", "बुधवासर", "गुरुवासर", "शुक्रवासर", "शनिवासर", "रविवासर"],
}

KARANA_CYCLE = {
    "en": ["Bava", "Balava", "Kaulava", "Taitila", "Garaja", "Vanija", "Vishti"],
    "hi": ["बव", "बालव", "कौलव", "तैतिल", "गर", "वणिज", "विष्टि"],
    "sa": ["बव", "बालव", "कौलव", "तैतिल", "गर", "वणिज", "विष्टि"],
}

SPECIAL_KARANA = {
    "en": {0: "Kimstughna", 57: "Shakuni", 58: "Chatushpada", 59: "Naga"},
    "hi": {0: "किंस्तुघ्न", 57: "शकुनि", 58: "चतुष्पद", 59: "नाग"},
    "sa": {0: "किंस्तुघ्न", 57: "शकुनि", 58: "चतुष्पद", 59: "नाग"},
}

PAKSHA_NAMES = {
    "Shukla": {"en": "Shukla", "hi": "शुक्ल", "sa": "शुक्ल"},
    "Krishna": {"en": "Krishna", "hi": "कृष्ण", "sa": "कृष्ण"},
}


def tri_name(table: dict[str, list[str]], index: int) -> dict[str, str]:
    return {key: table[key][index] for key in LANG_KEYS}


def karana_name(index: int) -> dict[str, str]:
    result: dict[str, str] = {}
    for key in LANG_KEYS:
        if index in SPECIAL_KARANA[key]:
            result[key] = SPECIAL_KARANA[key][index]
        else:
            result[key] = KARANA_CYCLE[key][(index - 1) % len(KARANA_CYCLE[key])]
    return result
